variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - python3.6 -m ensurepip
  - python3.6 -m virtualenv venv
  - source venv/bin/activate
  - python3.6 -m pip install poetry
  
test:
  image: python:3.6

  script:
    - set -e
    - poetry install
    - poetry run python -m pytest test
  tags:
    - docker

build_doc:
  script:
    - set -e
    - poetry install
    - poetry run mkdocs build
    - cp -r site/* /afs/wsi/home/gerum/public_html/autojail
  tags:
    - afs
    
