stages:
  - sca
  - test
  - deploy_test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - python3 -m ensurepip --user
  - python3 -m pip install virtualenv --user
  - python3 -m virtualenv venv
  - source venv/bin/activate
  - python3 -m pip install poetry

run_pre_commit:
  image: python:3.6
  stage: sca
  script:
    - set -e
    - poetry install
    - poetry run pre-commit run -a
  tags:
    - docker

test:
  image: python:3.6
  stage: test
  script:
    - set -e
    - apt-get update
    - apt-get install device-tree-compiler -y
    - poetry install
    - poetry run python -m pytest --cov=autojail test
  tags:
    - docker

test_python_latest:
  image: python:latest
  stage: test
  script:
    - set -e
    - apt-get update
    - apt-get install device-tree-compiler -y
    - poetry install
    - poetry run python -m pytest --cov=autojail test
  tags:
    - docker


test_with_qemu:
  image: ubuntu:20.04
  stage: deploy_test
  before_script:
    - export  DEBIAN_FRONTEND=noninteractive 
    - apt-get update -y 
    - apt-get upgrade -y 
    - apt-get install -y qemu-system-arm netcat-openbsd python3-dev python3-pip git gcc-aarch64-linux-gnu wget build-essential
    - python3 -m pip install virtualenv --user
    - python3 -m virtualenv venv
    - source venv/bin/activate
    - python3 -m pip install poetry
  script:
    - set -e
    - apt-get update
    - apt-get install device-tree-compiler -y
    - poetry install
    - poetry run python -m pytest --cov=autojail test
  tags:
    - docker
  only:
    - master
    - merge_requests

build_doc:
  script:
    - set -e
    - poetry install
    - poetry run mkdocs build
    - mkdir -p /afs/wsi/home/gerum/public_html/autojail
    - cp -r site/* /afs/wsi/home/gerum/public_html/autojail
  stage: deploy
  tags:
    - afs

  only:
    - master
