stages:
  - sca
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get install device-tree-compiler -y 
  - python3 -m ensurepip --user
  - python3 -m pip install virtualenv --user
  - python3 -m virtualenv venv
  - source venv/bin/activate
  - python3 -m pip install poetry
  
run_pre_commit: 
  image: python:3.6
  stage: sca
  script: 
    - set -e 
    - poetry install 
    - poetry run pre-commit
  tags:
    - docker

test:
  image: python:3.6
  stage: test
  script:
    - set -e
    - poetry install
    - poetry run python -m pytest test
  tags:
    - docker

test_python_latest:
  image: python:latest
  stage: test
  script:
    - set -e
    - poetry install
    - poetry run python -m pytest test
  tags:
    - docker

  
build_doc:
  script:
    - set -e
    - poetry install
    - poetry run mkdocs build
    - cp -r site/* /afs/wsi/home/gerum/public_html/autojail
  stage: deploy
  tags:
    - afs
    
  only:
    refs:
      - master
