image: python:3.6

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - python3.6 -m ensurepip
  - python3.6 -m pip install poetry
  
test:
  script:
    - set -e
    - poetry install
    - poetry run python -m pytest test
  tags:
    - docker