[tool.poetry]
name = "autojailhouse"
version = "0.1.0"
description = "Automatic jailhouse configuration for ARM based SOCs"
authors = ["Christoph Gerum <christoph.gerum@uni-tuebingen.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
automate = {path = "external/automate"}
pre-commit = "^1.21.0"

[tool.poetry.dev-dependencies]
invoke = "^1.4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


