[tool.poetry]
name = "autojailhouse"
version = "0.1.0"
description = "Automatic jailhouse configuration for ARM based SOCs"
authors = ["Christoph Gerum <christoph.gerum@uni-tuebingen.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
invoke = "^1.4.0"
automate = {git = "git@atreus.informatik.uni-tuebingen.de:ties/timing/schrank/automate.git"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


